<?php require 'templates/header.phtml' ?>

<?php
if (isset($error)) {
    echo $error;
}
?>

<?php foreach ($clubes as $club) : ?>
    <ul>
        <li>
            <div class="form-editar-club">
                <a class="palabraEditarClub"><?= $club->Club ?></a>
                <a class='botones' href='eliminarClub/<?= $club->club_id ?>'>Eliminar</a>
                <div>
                    <form action="editarClub/<?= $club->club_id ?>" method="POST">
                        <label>Editar nombre del Club</label>
                        <input name="clubName" type="text">
                        <button type="submit">Editar</button>
                    </form>
                </div>
            </div>
        </li>
    </ul>
<?php endforeach  ?>

<?php require 'templates/formClubes.phtml' ?>

<?php require 'templates/footer.phtml' ?>