<?php require 'templates/header.phtml' ?>


<?php foreach ($jugadores as $jugador): ?>

        <ul>
        <li>
            <a><?=$jugador->Nombre_Apellido?></a>
             <a class='botones' href='eliminarJugador/<?=$jugador->id_jugador?>'>Eliminar Jugador</a>
             <a class='botones' href='showEditarJugador/<?=$jugador->id_jugador?>'>Editar Jugador</a>
             
             <?php if(isset ($error))
                $error;
             ?>
       
        </li>
        </ul>

<?php endforeach ?>


<ul>
<li>    
        <a class='botones' href='showAgregarJugador/'>Agregar Jugador</a>    
</li>
</ul>

<?php require 'templates/footer.phtml' ?>