<?php require_once ('header.phtml')?>

<?php

    foreach ($clubes as $club){
        ?>
        <ul class='list-group'>
        <li class='list-group-item'>
            <div class="lista">
                <a class="header_button" href='jugadores_club/<?=$club->club_id?>'> <?= $club->Club?></a>
            </div>
            
        </li>
        </ul>

    <?php
    } 
        
?>

<?php require_once ('footer.phtml'); 