<?php require_once 'templates/header.phtml' ?>

<?php if(isset($error)){
   echo $error;
}
    ?>
    <form action="agregarJugador" method="POST">
        <div class="form">
            <label>FORMULARIO PARA AGREGAR JUGADOR</label>
            <div>
            <input placeholder="Ingrese edad del jugador" name="edad" type="number" min="16" max="60" style="width: 170px;">
            </div>
            <div>
            <input placeholder="Ingrese cantidad de Goles" name="goles" type="number" min="0" style="width: 170px;">
            </div>
            <div>
            <input placeholder="Ingrese nombre del jugador" name="jugadorName" type="text" style="width: 170px;">
            </div>
            <div>
            <input placeholder=" Ingrese club valido" name="clubName" type="text" style="width: 170px;">
            </div>
            <button type="submit">Guardar</button>
        </div>
        
    </form> 

<?php

?>
    

<?php require_once 'templates/footer.phtml' ?>