<?php require_once 'templates/header.phtml' ?>

<?php if(isset($error)){
   echo $error;
}

    ?>
    <form action="agregarJugador" method="POST">
        <div class="formulario">
            <label>Edad</label>
                <input name="edad" type="number" min="16" max="60">
            <label>Cantidad de Goles</label>
                    <input name="goles" type="number" min="0">
            <label> Nombre </label>
                    <input name="jugadorName" type="text">
            <label> Inserte Club Valido </label>
                    <input name="clubName" type="text">
    
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form> 

<?php

?>
    

<?php require_once 'templates/footer.phtml' ?>