<?php require_once 'templates/header.phtml' ?>

<?php if(isset($error)){
   echo $error;
   
}

    ?>
  

    <form action="editarJugador" method="POST">
    
        <div class="formJugador">
            <div>
            <h1><?=$jugador->Nombre_Apellido?></h1>
            </div>

            <div>
                <input placeholder="Editar Edad" name="edad" type="number" min="16" max="60" style="width: 170px;">
            </div>
            <div>
                    <input placeholder="Editar cantidad de goles" name="goles" type="number" min="0" style="width: 170px;">
            </div>
            <div>
                    <input placeholder="Editar Nombre del jugador" name="jugadorName" type="text" style="width: 170px;">
            </div>
           <div>
                    <input placeholder="Editar Club del jugador" name="clubName" type="text" style="width: 170px;">
                    <input type="hidden" name="club_id" value=<?=$jugador->club_id?>>
                    <input type="hidden" name="jugador_id" value=<?=$jugador->id_jugador?>>
           </div>
                    <button type="submit">Guardar</button>
        </div>
        
    </form> 

<?php

?>
    

<?php require_once 'templates/footer.phtml' ?>