<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href=<?php echo BASE_URL; ?>>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://localhost/tpe-especial-web2/css/style.css?v=1.1">
    <title>Estadisticas_FUTARG</title>
</head>

<body>
    <header>
       
            <a href="menu" class="header_button">FUT ARG</a>
       
       
            <a href="jugadores" class="header_button">Jugadores</a>
      
        <?php
        ?>
    
<?php
    AuthHelper::init() ;
      
    if (isset($_SESSION['USER_NAME']) && $_SESSION['USER_NAME'] == true): ?> 
  
     <a class= "header_button" href="admin">ADMIN</a>
      <a class= "header_button" href="logout" >Logout</a>
<?php else: ?>
      <a class="header_button" href="login" >Login</a>
<?php endif; ?>
</header>







