<?php require_once ('header.phtml'); ?>

<?php

if(isset($error)){
    
    echo $error;

} else {
?>
    <h1> <?=$club->Club?></h1>

<?php
    foreach ($jugadores as $jugador){ 
        ?>
        <ul>
        <li>
            <div class="lsita">
                <a href='info_jugador/<?=$jugador->id_jugador?>'><?=$jugador->Nombre_Apellido?></a>
            </div>
            
        </li>
        </ul>
    <?php
    }
}
 require_once ('footer.phtml');
?>