<?php require_once  ('header.phtml');?>

 
    <table class='tabla_jugador'>
        <tr>
            <th>Nombre Y apellido</th>
            <th>Edad</th>
            <th>Goles</th>
            <th>Club</th>
            </tr>
        <tr>
            <th><?= $jugador->Nombre_Apellido ?> </th>
            <th><?= $jugador->Edad ?> </th>
            <th><?= $jugador->Goles ?> </th>
            <th><?= $club->Club ?> </th>
        </tr>
    </table>
        

 <?php  require_once ('footer.phtml');?>
