<?php require_once ('header.phtml'); ?>
<?php

    foreach ($jugadores as $jugador){
        ?>
        <ul>
            <li>
                <div class='lista'>
                    <?php 
                    $i = 0;
                    $var = false;
                    
                    while($var == false && $i < count($clubes)){
                        if ($jugador->club_id == $clubes[$i]->club_id){
                            $var= true; ?>
                            
                            <a><?=$clubes[$i]->Club?></a>    
                        <?php
                        }
                        $i++;
                    } ?>
                    <a class='header_button' href='info_jugador/<?=$jugador->id_jugador?>'><?=$jugador->Nombre_Apellido?></a>  
                </div>     
            </li>
        </ul>      
    <?php
    }              
    ?> 
          
       

<?php require_once ('footer.phtml');?>
    