<?php require_once ('header.phtml');

    echo "
    <table class='tabla_jugador'>
        <tr class='parte_de_arriba'>
            <th>Nombre Y apellido</th>
            <th>Edad</th>
                <th>Goles</th>
            </tr>
        <tr class='parte_de_abajo'>
            <td>$jugador->Nombre_Apellido</td>
            <td>$jugador->Edad</td>
            <td>$jugador->Goles</td>
        </tr>
    </table>";
        

 require_once ('footer.phtml');
?>