<?php require 'header.phtml' ?>

<div class="form">
    <form method="POST" action="auth">
        <div>
            <label for="usuario">Usuario</label>
            <input type="usuario" id="usuario" name="usuario" aria-describedby="emailHelp">
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit">Entrar</button>
    </form>
</div>

<?php require 'footer.phtml'?>

